DROP TABLE IF EXISTS FORMATEUR;

DROP TABLE IF EXISTS FORMATION;

DROP TABLE IF EXISTS SESSION;

# -----------------------------------------------------------------------------
#       TABLE : FORMATEUR
# -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS FORMATEUR
(
    ID_FORMATEUR INTEGER(2) NOT NULL AUTO_INCREMENT ,
    NOM CHAR(32) NULL  ,
    PRENOM CHAR(32) NULL  ,
    TRIGRAMME CHAR(32) NULL  ,
    COMPETENCE CHAR(32) NULL  ,
    SALAIRE_NET BIGINT(4) NULL  ,
    URSSAF CHAR(32) NULL
    , PRIMARY KEY (ID_FORMATEUR)
    )
    comment = "";

# -----------------------------------------------------------------------------
#       TABLE : FORMATION
# -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS FORMATION
(
    ID_FORMATION INTEGER(2) NOT NULL AUTO_INCREMENT ,
    NOM CHAR(255) NULL  ,
    NB_HEURES BIGINT(4) NULL  ,
    PRIX_FORMATION BIGINT(4) NULL  ,
    MATERIELS TEXT NULL
    , PRIMARY KEY (ID_FORMATION)
    )
    comment = "";

# -----------------------------------------------------------------------------
#       TABLE : SESSION
# -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS SESSION
(
    ID_SESSION INTEGER(2) NOT NULL AUTO_INCREMENT ,
    ID_FORMATEUR INTEGER(2) NOT NULL  ,
    ID_STATUT INTEGER(2) NOT NULL  ,
    ID_FORMATION INTEGER(2) NOT NULL  ,
    LIEU_SESSION CHAR(255) NULL  ,
    NB_STAGIAIRE INTEGER(2) NULL  ,
    PRIX_DEVIS BIGINT(4) NULL  ,
    DEVIS CHAR(32) NULL  ,
    BON_DE_COMMANDE CHAR(32) NULL  ,
    NOTE TEXT NULL
    , PRIMARY KEY (ID_SESSION)
    )
    comment = "";


# -----------------------------------------------------------------------------
#       CREATION DES REFERENCES DE TABLE
# -----------------------------------------------------------------------------


ALTER TABLE SESSION
    ADD FOREIGN KEY FK_SESSION_FORMATEUR (ID_FORMATEUR)
    REFERENCES FORMATEUR (ID_FORMATEUR) ;


ALTER TABLE TO_KNOW
    ADD FOREIGN KEY FK_TO_KNOW_FORMATEUR (ID_FORMATEUR)
    REFERENCES FORMATEUR (ID_FORMATEUR) ;


ALTER TABLE TO_KNOW
    ADD FOREIGN KEY FK_TO_KNOW_FORMATION (ID_FORMATION)
    REFERENCES FORMATION (ID_FORMATION) ;


ALTER TABLE DEMANDER
    ADD FOREIGN KEY FK_DEMANDER_FORMATION (ID_FORMATION)
    REFERENCES FORMATION (ID_FORMATION) ;


ALTER TABLE SESSION
    ADD FOREIGN KEY FK_SESSION_FORMATION (ID_FORMATION)
    REFERENCES FORMATION (ID_FORMATION) ;


ALTER TABLE FORMATION_STANDARD
    ADD FOREIGN KEY FK_FORMATION_STANDARD_FORMATION (ID_FORMATION)
    REFERENCES FORMATION (ID_FORMATION) ;


ALTER TABLE FORMATION_PERSO
    ADD FOREIGN KEY FK_FORMATION_PERSO_FORMATION (ID_FORMATION)
    REFERENCES FORMATION (ID_FORMATION) ;


ALTER TABLE SESSION
    ADD FOREIGN KEY FK_SESSION_STATUT (ID_STATUT)
    REFERENCES STATUT (ID_STATUT) ;


ALTER TABLE COMMANDER
    ADD FOREIGN KEY FK_COMMANDER_SESSION (ID_SESSION)
    REFERENCES SESSION (ID_SESSION) ;


ALTER TABLE TO_DO_LIST
    ADD FOREIGN KEY FK_TO_DO_LIST_SESSION (ID_SESSION)
    REFERENCES SESSION (ID_SESSION) ;


ALTER TABLE ETRE_PAYER
    ADD FOREIGN KEY FK_ETRE_PAYER_SESSION (ID_SESSION)
    REFERENCES SESSION (ID_SESSION) ;


ALTER TABLE DATE_SESSION
    ADD FOREIGN KEY FK_DATE_SESSION_SESSION (ID_SESSION)
    REFERENCES SESSION (ID_SESSION) ;

